# Site settings
title:        BLANDIFULL
description:  Battaniyeye, günlük yaşama dair .. 
keywords:     Modern, Blogging, Fun,Battaniye, Bebek, Yetişkin,TV Battaniyesi, Bebek Battaniyesi
author:       Nisaseren Aksu
baseurl:      "Blandifull" # the subpath of your site, e.g. /blog/
url:          "https://nisaseren.github.io" # the base hostname & protocol for your site
permalink:    /:title/

# Comments
disqus_shortname:   eyyupalkis


# Google Analytics
google_analytics: #UA-152797941-1

jekyll-mentions:
base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
